//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Product_Form
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.OwnProducts = new HashSet<OwnProduct>();
        }
    
        public int Id { get; set; }
        public string CompanyName { get; set; }
        public string Manufacture { get; set; }
        public string Website { get; set; }
        public string Email { get; set; }
        public string StreetAddress { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public string StateProvinceRegion { get; set; }
        public string ZipPostlCode { get; set; }
        public int Country_Id_fk { get; set; }
        public string Phone { get; set; }
        public string FAX { get; set; }
    
        public virtual Country Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OwnProduct> OwnProducts { get; set; }
    }
}
