using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Product_Form
{
    public  class DropDown
    {
        ProductFormEntities db;
        public DropDown()
        {
             db = new ProductFormEntities();    
        }

        public List<Color>  listColors()
        {
            var list = db.Colors.ToList();
            return list;
        }

        public List<Material> listMaterial()
        {
            var list = db.Materials.ToList();
            return list;
        }

        public List<Country> countries()
        {
            List<Country> list = new List<Country>()
            {
                new Country(){id=1,name="Afghanistan",value="AF"},
                new Country(){id=2,name="Albania",value="AL"},
                new Country(){id=3,name="Algeria",value="DZ"},
                new Country(){id=4,name="American Samoa",value="AS"},
                new Country(){id=5,name="Andorra",value="AD"},
                new Country(){id=6,name="Angola",value="AO"},
                new Country(){id=7,name="Anguilla",value="AI"},
                new Country(){id=8,name="Antarctica",value="AQ"},
                new Country(){id=9,name="Antigua And Barbuda",value="AG"},
                new Country(){id=10,name="Argentina",value="AR"},
                new Country(){id=11,name="Armenia",value="AM"},
                new Country(){id=12,name="Aruba",value="AW"},
                new Country(){id=13,name="Australia",value="AU"},
                new Country(){id=14,name="Austria",value="AT"},
                new Country(){id=15,name="Azerbaijan",value="AZ"},
                new Country(){id=16,name="Bahamas",value="BS"},
                new Country(){id=17,name="Bahrain",value="BH"},
                new Country(){id=18,name="Bangladesh",value="BD"},
                new Country(){id=19,name="Barbados",value="BB"},
                new Country(){id=20,name="Belarus",value="BY"},
                new Country(){id=21,name="Belgium",value="BE"},
                new Country(){id=22,name="Belize",value="BZ"},
                new Country(){id=23,name="Benin",value="BJ"},
                new Country(){id=24,name="Bermuda",value="BM"},
                new Country(){id=25,name="Bhutan",value="BT"},
                new Country(){id=26,name="Bolivia",value="BO"},
                new Country(){id=27,name="Bosnia And Herzegowina",value="BA"},
                new Country(){id=28,name="Botswana",value="BW"},
                new Country(){id=29,name="Bouvet Island",value="BV"},
                new Country(){id=30,name="Brazil",value="BR"},
                new Country(){id=31,name="British Indian Ocean Territory",value="IO"},
                new Country(){id=32,name="Brunei Darussalam",value="BN"},
                new Country(){id=33,name="Bulgaria",value="BG"},
                new Country(){id=34,name="Burkina Faso",value="BF"},
                new Country(){id=35,name="Burundi",value="BI"},
                new Country(){id=36,name="Cambodia",value="KH"},
                new Country(){id=37,name="Cameroon",value="CM"},
                new Country(){id=38,name="Canada",value="CA"},
                new Country(){id=39,name="Cape Verde",value="CV"},
                new Country(){id=40,name="Cayman Islands",value="KY"},
                new Country(){id=41,name="Central African Republic",value="CF"},
                new Country(){id=42,name="Chad",value="TD"},
                new Country(){id=43,name="Chile",value="CL"},
                new Country(){id=44,name="China",value="CN"},
                new Country(){id=45,name="Christmas Island",value="CX"},
                new Country(){id=46,name="Cocos (Keeling) Islands",value="CC"},
                new Country(){id=47,name="Colombia",value="CO"},
                new Country(){id=48,name="Comoros",value="KM"},
                new Country(){id=49,name="Congo",value="CG"},
                new Country(){id=50,name="Cook Islands",value="CK"},
                new Country(){id=51,name="Costa Rica",value="CR"},
                new Country(){id=52,name="Cote D'Ivoire",value="CI"},
                new Country(){id=53,name="Croatia (Local Name: Hrvatska)",value="HR"},
                new Country(){id=54,name="Cuba",value="CU"},
                new Country(){id=55,name="Cyprus",value="CY"},
                new Country(){id=56,name="Czech Republic",value="CZ"},
                new Country(){id=57,name="Denmark",value="DK"},
                new Country(){id=58,name="Djibouti",value="DJ"},
                new Country(){id=59,name="Dominica",value="DM"},
                new Country(){id=60,name="Dominican Republic",value="DO"},
                new Country(){id=61,name="East Timor",value="TP"},
                new Country(){id=62,name="Ecuador",value="EC"},
                new Country(){id=63,name="Egypt",value="EG"},
                new Country(){id=64,name="El Salvador",value="SV"},
                new Country(){id=65,name="Equatorial Guinea",value="GQ"},
                new Country(){id=66,name="Eritrea",value="ER"},
                new Country(){id=67,name="Estonia",value="EE"},
                new Country(){id=68,name="Ethiopia",value="ET"},
                new Country(){id=69,name="Falkland Islands (Malvinas)",value="FK"},
                new Country(){id=70,name="Faroe Islands",value="FO"},
                new Country(){id=71,name="Fiji",value="FJ"},
                new Country(){id=72,name="Finland",value="FI"},
                new Country(){id=73,name="France",value="FR"},
                new Country(){id=74,name="French Guiana",value="GF"},
                new Country(){id=75,name="French Polynesia",value="PF"},
                new Country(){id=76,name="French Southern Territories",value="TF"},
                new Country(){id=77,name="Gabon",value="GA"},
                new Country(){id=78,name="Gambia",value="GM"},
                new Country(){id=79,name="Georgia",value="GE"},
                new Country(){id=80,name="Germany",value="DE"},
                new Country(){id=81,name="Ghana",value="GH"},
                new Country(){id=82,name="Gibraltar",value="GI"},
                new Country(){id=83,name="Greece",value="GR"},
                new Country(){id=84,name="Greenland",value="GL"},
                new Country(){id=85,name="Grenada",value="GD"},
                new Country(){id=86,name="Guadeloupe",value="GP"},
                new Country(){id=87,name="Guam",value="GU"},
                new Country(){id=88,name="Guatemala",value="GT"},
                new Country(){id=89,name="Guinea",value="GN"},
                new Country(){id=90,name="Guinea-Bissau",value="GW"},
                new Country(){id=91,name="Guyana",value="GY"},
                new Country(){id=92,name="Haiti",value="HT"},
                new Country(){id=93,name="Heard And Mc Donald Islands",value="HM"},
                new Country(){id=94,name="Holy See (Vatican City State)",value="VA"},
                new Country(){id=95,name="Honduras",value="HN"},
                new Country(){id=96,name="Hong Kong",value="HK"},
                new Country(){id=97,name="Hungary",value="HU"},
                new Country(){id=98,name="Icel And",value="IS"},
                new Country(){id=99,name="India",value="IN"},
                new Country(){id=100,name="Indonesia",value="ID"},
                new Country(){id=101,name="Iran (Islamic Republic Of)",value="IR"},
                new Country(){id=102,name="Iraq",value="IQ"},
                new Country(){id=103,name="Ireland",value="IE"},
                new Country(){id=104,name="Israel",value="IL"},
                new Country(){id=105,name="Italy",value="IT"},
                new Country(){id=106,name="Jamaica",value="JM"},
                new Country(){id=107,name="Japan",value="JP"},
                new Country(){id=108,name="Jordan",value="JO"},
                new Country(){id=109,name="Kazakhstan",value="KZ"},
                new Country(){id=110,name="Kenya",value="KE"},
                new Country(){id=111,name="Kiribati",value="KI"},
                new Country(){id=112,name="Korea, Dem People'S Republic",value="KP"},
                new Country(){id=113,name="Korea, Republic Of",value="KR"},
                new Country(){id=114,name="Kuwait",value="KW"},
                new Country(){id=115,name="Kyrgyzstan",value="KG"},
                new Country(){id=116,name="Lao People'S Dem Republic",value="LA"},
                new Country(){id=117,name="Latvia",value="LV"},
                new Country(){id=118,name="Lebanon",value="LB"},
                new Country(){id=119,name="Lesotho",value="LS"},
                new Country(){id=120,name="Liberia",value="LR"},
                new Country(){id=121,name="Libyan Arab Jamahiriya",value="LY"},
                new Country(){id=122,name="Liechtenstein",value="LI"},
                new Country(){id=123,name="Lithuania",value="LT"},
                new Country(){id=124,name="Luxembourg",value="LU"},
                new Country(){id=125,name="Macau",value="MO"},
                new Country(){id=126,name="Macedonia",value="MK"},
                new Country(){id=127,name="Madagascar",value="MG"},
                new Country(){id=128,name="Malawi",value="MW"},
                new Country(){id=129,name="Malaysia",value="MY"},
                new Country(){id=130,name="Maldives",value="MV"},
                new Country(){id=131,name="Mali",value="ML"},
                new Country(){id=132,name="Malta",value="MT"},
                new Country(){id=133,name="Marshall Islands",value="MH"},
                new Country(){id=134,name="Martinique",value="MQ"},
                new Country(){id=135,name="Mauritania",value="MR"},
                new Country(){id=136,name="Mauritius",value="MU"},
                new Country(){id=137,name="Mayotte",value="YT"},
                new Country(){id=138,name="Mexico",value="MX"},
                new Country(){id=139,name="Micronesia, Federated States",value="FM"},
                new Country(){id=140,name="Moldova, Republic Of",value="MD"},
                new Country(){id=141,name="Monaco",value="MC"},
                new Country(){id=142,name="Mongolia",value="MN"},
                new Country(){id=143,name="Montserrat",value="MS"},
                new Country(){id=144,name="Morocco",value="MA"},
                new Country(){id=145,name="Mozambique",value="MZ"},
                new Country(){id=146,name="Myanmar",value="MM"},
                new Country(){id=147,name="Namibia",value="NA"},
                new Country(){id=148,name="Nauru",value="NR"},
                new Country(){id=149,name="Nepal",value="NP"},
                new Country(){id=150,name="Netherlands",value="NL"},
                new Country(){id=151,name="Netherlands Ant Illes",value="AN"},
                new Country(){id=152,name="New Caledonia",value="NC"},
                new Country(){id=153,name="New Zealand",value="NZ"},
                new Country(){id=154,name="Nicaragua",value="NI"},
                new Country(){id=155,name="Niger",value="NE"},
                new Country(){id=156,name="Nigeria",value="NG"},
                new Country(){id=157,name="Niue",value="NU"},
                new Country(){id=158,name="Norfolk Island",value="NF"},
                new Country(){id=159,name="Northern Mariana Islands",value="MP"},
                new Country(){id=160,name="Norway",value="NO"},
                new Country(){id=161,name="Oman",value="OM"},
                new Country(){id=162,name="Pakistan",value="PK"},
                new Country(){id=163,name="Palau",value="PW"},
                new Country(){id=164,name="Panama",value="PA"},
                new Country(){id=165,name="Papua New Guinea",value="PG"},
                new Country(){id=166,name="Paraguay",value="PY"},
                new Country(){id=167,name="Peru",value="PE"},
                new Country(){id=168,name="Philippines",value="PH"},
                new Country(){id=169,name="Pitcairn",value="PN"},
                new Country(){id=170,name="Poland",value="PL"},
                new Country(){id=171,name="Portugal",value="PT"},
                new Country(){id=172,name="Puerto Rico",value="PR"},
                new Country(){id=173,name="Qatar",value="QA"},
                new Country(){id=174,name="Reunion",value="RE"},
                new Country(){id=175,name="Romania",value="RO"},
                new Country(){id=176,name="Russian Federation",value="RU"},
                new Country(){id=177,name="Rwanda",value="RW"},
                new Country(){id=178,name="Saint K Itts And Nevis",value="KN"},
                new Country(){id=179,name="Saint Lucia",value="LC"},
                new Country(){id=180,name="Saint Vincent, The Grenadines",value="VC"},
                new Country(){id=181,name="Samoa",value="WS"},
                new Country(){id=182,name="San Marino",value="SM"},
                new Country(){id=183,name="Sao Tome And Principe",value="ST"},
                new Country(){id=184,name="Saudi Arabia",value="SA"},
                new Country(){id=185,name="Senegal",value="SN"},
                new Country(){id=186,name="Seychelles",value="SC"},
                new Country(){id=187,name="Sierra Leone",value="SL"},
                new Country(){id=188,name="Singapore",value="SG"},
                new Country(){id=189,name="Slovakia (Slovak Republic)",value="SK"},
                new Country(){id=190,name="Slovenia",value="SI"},
                new Country(){id=191,name="Solomon Islands",value="SB"},
                new Country(){id=192,name="Somalia",value="SO"},
                new Country(){id=193,name="South Africa",value="ZA"},
                new Country(){id=194,name="South Georgia , S Sandwich Is.",value="GS"},
                new Country(){id=195,name="Spain",value="ES"},
                new Country(){id=196,name="Sri Lanka",value="LK"},
                new Country(){id=197,name="St. Helena",value="SH"},
                new Country(){id=198,name="St. Pierre And Miquelon",value="PM"},
                new Country(){id=199,name="Sudan",value="SD"},
                new Country(){id=200,name="Suriname",value="SR"},
                new Country(){id=201,name="Svalbard, Jan Mayen Islands",value="SJ"},
                new Country(){id=202,name="Sw Aziland",value="SZ"},
                new Country(){id=203,name="Sweden",value="SE"},
                new Country(){id=204,name="Switzerland",value="CH"},
                new Country(){id=205,name="Syrian Arab Republic",value="SY"},
                new Country(){id=206,name="Taiwan",value="TW"},
                new Country(){id=207,name="Tajikistan",value="TJ"},
                new Country(){id=208,name="Tanzania, United Republic Of",value="TZ"},
                new Country(){id=209,name="Thailand",value="TH"},
                new Country(){id=210,name="Togo",value="TG"},
                new Country(){id=211,name="Tokelau",value="TK"},
                new Country(){id=212,name="Tonga",value="TO"},
                new Country(){id=213,name="Trinidad And Tobago",value="TT"},
                new Country(){id=214,name="Tunisia",value="TN"},
                new Country(){id=215,name="Turkey",value="TR"},
                new Country(){id=216,name="Turkmenistan",value="TM"},
                new Country(){id=217,name="Turks And Caicos Islands",value="TC"},
                new Country(){id=218,name="Tuvalu",value="TV"},
                new Country(){id=219,name="Uganda",value="UG"},
                new Country(){id=220,name="Ukraine",value="UA"},
                new Country(){id=221,name="United Arab Emirates",value="AE"},
                new Country(){id=222,name="United Kingdom",value="GB"},
                new Country(){id=223,name="United States",value="US"},
                new Country(){id=224,name="United States Minor Is.",value="UM"},
                new Country(){id=225,name="Uruguay",value="UY"},
                new Country(){id=226,name="Uzbekistan",value="UZ"},
                new Country(){id=227,name="Vanuatu",value="VU"},
                new Country(){id=228,name="Venezuela",value="VE"},
                new Country(){id=229,name="Viet Nam",value="VN"},
                new Country(){id=230,name="Virgin Islands (British)",value="VG"},
                new Country(){id=231,name="Virgin Islands (U.S.)",value="VI"},
                new Country(){id=232,name="Wallis And Futuna Islands",value="WF"},
                new Country(){id=233,name="Western Sahara",value="EH"},
                new Country(){id=234,name="Yemen",value="YE"},
                new Country(){id=235,name="Zaire",value="ZR"},
                new Country(){id=236,name="Zambia",value="ZM"},
                new Country(){id=237,name="Zimbabwe",value="ZW"},

            };
            return list;
        }

    }
}
