//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Product_Form
{
    using System;
    using System.Collections.Generic;
    
    public partial class OwnProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OwnProduct()
        {
            this.Images = new HashSet<Image>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ProductType_Id_fk { get; set; }
        public string ProductTittle { get; set; }
        public Nullable<int> Brand_Id_fk { get; set; }
        public Nullable<int> Color_Id_fk { get; set; }
        public Nullable<int> Material_Id_fk { get; set; }
        public Nullable<bool> RFIDProtected { get; set; }
        public Nullable<bool> TSAApprovedLock { get; set; }
        public Nullable<bool> CheckPointFriendly { get; set; }
        public Nullable<bool> Expandable { get; set; }
        public Nullable<bool> WaterResistance { get; set; }
        public Nullable<bool> RetractableHandle { get; set; }
        public string DescribeMaterial { get; set; }
        public Nullable<float> Price { get; set; }
        public Nullable<float> Width { get; set; }
        public Nullable<float> Depth { get; set; }
        public Nullable<float> Height { get; set; }
        public Nullable<float> Weight { get; set; }
        public Nullable<bool> Box { get; set; }
        public Nullable<bool> Wrap { get; set; }
        public Nullable<bool> NoPackaging { get; set; }
        public Nullable<bool> AirTransportation { get; set; }
        public Nullable<bool> ShipTransportation { get; set; }
        public Nullable<bool> Train { get; set; }
        public Nullable<bool> Truck { get; set; }
        public Nullable<int> Company_Id_fk { get; set; }
        public Nullable<int> CountryofOrgin_Id_fk { get; set; }
        public Nullable<int> Barcode_Id_fk { get; set; }
        public Nullable<bool> Bag { get; set; }
        public string SpecialPackingInstructions { get; set; }
    
        public virtual Barcode Barcode { get; set; }
        public virtual Brand Brand { get; set; }
        public virtual Color Color { get; set; }
        public virtual Country Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Image> Images { get; set; }
        public virtual Material Material { get; set; }
        public virtual ProductType ProductType { get; set; }
        public virtual Company Company { get; set; }
    }
}
